version: 0.1

environment_variables:
  plaintext:
    BAD_JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    AWS_DEFAULT_REGION: "us-east-1"
    SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:061121813127:build-notifications"

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Running the build!
      - chmod +x gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $CODEBUILD_SRC_DIR
      - aws sns publish --topic-arn $SNS_TOPIC_ARN --subject 'AWS CodeBuild - Build Completed' --message 'The build has completed. For build details, go check out stuff on AWS (TODO: fill this in later)' 

artifacts:
  files:
    - 'buildspec.yml'
  discard-paths: no
