version: 0.1

environment_variables:
  plaintext:
    #JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Running the build!
      #- chmod +x gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $CODEBUILD_SRC_DIR
artifacts:
  files:
      - 'buildspec.yml'
  discard-paths: no
