version: 0.1

environment_variables:
  plaintext:

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Running the build!
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $CODEBUILD_SRC_DIR
artifacts:
  files:
      - 'buildspec.yml'
  discard-paths: no
